services:
  education-content-service:
    container_name: education-content-service
    build:
      context: ./backend/EducationContentService
      dockerfile: Dockerfile
    ports:
      - "6185:6185"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:6185
    env_file:
      - education.service.env
    restart: always
  
  seq:
    container_name: seqEducationContent
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:5341"
      - "8081:80"
    restart: always
    
  postgress:
    container_name: postgres-serookiy-tech
    image: postgres
    environment:
      POSTGRES_DB: serookiy_tech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
     